In [1]:
import numpy as np

In [3]:
A = np.array([[0,3,-4],[-3,0,1],[4,-1,0]])

In [4]:
A

array([[ 0,  3, -4],
       [-3,  0,  1],
       [ 4, -1,  0]])

In [5]:
A.T*A

array([[  0,  -9, -16],
       [ -9,   0,  -1],
       [-16,  -1,   0]])

In [6]:
A*A.T

array([[  0,  -9, -16],
       [ -9,   0,  -1],
       [-16,  -1,   0]])

In [8]:
A.T+A

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])