In [1]:
from sklearn.metrics import roc_curve, auc

In [2]:
import matplotlib.pyplot as plt

In [3]:
y_label = ([1, 1, 1, 2, 2, 2])
y_pre = ([0.3, 0.5, 0.9, 0.8, 0.4, 0.6])

In [5]:
fpr, tpr, thresholds = roc_curve(y_label, y_pre, pos_label=2)

In [ ]:
# for i, value in enumerate(thresholds):
    # print("%f %f %f" % (fpr[i], tpr[i],


In [6]:
import numpy as np
from sklearn.metrics import accuracy_score, confusion_matrix, roc_auc_score, roc_curve

In [7]:
n = 10000
ratio = .95
n_0 = int((1-ratio)*n)
n_1 = int(ratio*n)

In [8]:
n_0, n_1

(500, 9500)

In [9]:
y = np.array([0] * n_0 + [1] * n_1)

In [10]:
y

array([0, 0, 0, ..., 1, 1, 1])

In [11]:
y_proba = np.array([1] * n)
y_pred = y_proba > .5

In [12]:
y_proba

array([1, 1, 1, ..., 1, 1, 1])

In [13]:
y_pred

array([ True,  True,  True, ...,  True,  True,  True])

In [14]:
print(f'accuracy score: {accuracy_score(y, y_pred)}')

accuracy score: 0.95


In [15]:
cf_mat = confusion_matrix(y, y_pred)
print('Confusion matrix')
print(cf_mat)
print(f'class 0 accuracy: {cf_mat[0][0]/n_0}')
print(f'class 1 accuracy: {cf_mat[1][1]/n_1}')

Confusion matrix
[[   0  500]
 [   0 9500]]
class 0 accuracy: 0.0
class 1 accuracy: 1.0
