In [8]:
import numpy as np
from numpy import loadtxt

In [2]:
dataA = loadtxt('data/classA_trn.dat')
dataB = loadtxt('data/classB_trn.dat')

In [4]:
len(dataA)

250

In [5]:
len(dataB)

100

In [7]:
type(dataA)

numpy.ndarray

In [11]:
dataYA = np.zeros((250, 1), int)

In [13]:
dataYB = np.ones((100, 1), int)

In [15]:
dataA = np.concatenate([dataA, dataYA], axis=1)

In [17]:
dataB = np.concatenate([dataB, dataYB], axis=1)

In [18]:
data = np.concatenate([dataA, dataB])

In [19]:
data

array([[-0.33171371,  0.57734411,  3.54717841,  0.        ],
       [ 2.70680861,  0.43402881,  4.71331105,  0.        ],
       [ 0.40465598,  2.62619979,  3.57616767,  0.        ],
       ...,
       [ 2.20526982,  0.47401295,  3.27001854,  1.        ],
       [ 1.8347271 ,  3.60125731,  1.55963864,  1.        ],
       [ 1.77159088,  1.18338445,  1.85177492,  1.        ]])

In [20]:
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis

In [21]:
dataA = loadtxt('data/classA_trn.dat')
dataB = loadtxt('data/classB_trn.dat')

In [22]:
dataX = np.concatenate([dataA, dataB])

In [23]:
dataX

array([[-0.33171371,  0.57734411,  3.54717841],
       [ 2.70680861,  0.43402881,  4.71331105],
       [ 0.40465598,  2.62619979,  3.57616767],
       ...,
       [ 2.20526982,  0.47401295,  3.27001854],
       [ 1.8347271 ,  3.60125731,  1.55963864],
       [ 1.77159088,  1.18338445,  1.85177492]])

In [25]:
dataY = np.concatenate([np.zeros((250, 1)), np.ones((100, 1))])

In [26]:
clf = QuadraticDiscriminantAnalysis()

In [28]:
clf.fit(dataX, dataY)

/home/sha/work/_p310/lib/python3.10/site-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


QuadraticDiscriminantAnalysis()

In [29]:
testA = np.loadtxt('data/classA_test.dat')
testB = np.loadtxt('data/classB_test.dat')

In [32]:
testYA = clf.predict(testA)

In [33]:
testYB = clf.predict(testB)

In [36]:
yaf = np.count_nonzero(testYA > 0.)

In [37]:
ra = (len(testYA) - yaf) / len(testYA)

In [38]:
ra

0.972

In [41]:
rb = (len(testYB) - np.count_nonzero(testYB < 1.)) / len(testYB)

In [42]:
rb

0.74

In [45]:
testYB < 1.

array([ True, False, False, False,  True, False, False, False, False,
        True, False, False, False, False, False, False,  True, False,
       False, False,  True,  True, False, False, False,  True, False,
        True,  True, False, False,  True, False, False, False,  True,
       False, False, False, False, False, False, False, False,  True,
       False,  True,  True, False, False, False, False, False,  True,
        True,  True, False, False, False,  True, False, False, False,
       False, False, False, False, False, False, False,  True, False,
       False, False, False, False, False,  True, False, False, False,
       False, False, False, False, False, False,  True,  True, False,
        True,  True, False, False, False, False,  True, False, False,
        True])

In [46]:
testYB

array([0., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 0.,
       1., 1., 1., 0., 0., 1., 1., 1., 0., 1., 0., 0., 1., 1., 0., 1., 1.,
       1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 0., 0., 1., 1., 1.,
       1., 1., 0., 0., 0., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 0., 0., 1., 0., 0., 1., 1., 1., 1., 0., 1., 1., 0.])

In [50]:
mean_A = np.mean(dataA, axis=0, keepdims=True)

In [51]:
mean_A

array([[0.93529521, 1.99390144, 4.02615068]])

In [53]:
mean_B = np.mean(dataB, axis=0, keepdims=True)

In [54]:
mean_B

array([[1.99478019, 2.19551431, 1.36429809]])

In [57]:
cov_A = np.cov(dataA.T)

In [58]:
cov_A

array([[ 0.95796805, -0.04108512,  0.08887932],
       [-0.04108512,  1.12853282, -0.05353524],
       [ 0.08887932, -0.05353524,  0.98545591]])

In [59]:
dataA

array([[-0.33171371,  0.57734411,  3.54717841],
       [ 2.70680861,  0.43402881,  4.71331105],
       [ 0.40465598,  2.62619979,  3.57616767],
       [ 0.38809626,  1.79640229,  3.59026913],
       [ 2.87952378,  2.37719337,  4.52006552],
       [ 0.79953092,  3.61834209,  4.84292465],
       [ 1.70857928,  3.21952667,  4.37209885],
       [-0.73006478,  0.94273942,  2.36173542],
       [ 1.52217072,  2.31387324,  6.24034629],
       [ 0.68056509,  3.21173076,  4.22571251],
       [-0.35533286,  2.33658602,  3.86372304],
       [ 2.38877425,  1.73785799,  4.94983806],
       [ 0.86840314,  0.45672549,  4.33225073],
       [ 0.99055398,  0.8817235 ,  3.83038874],
       [ 1.52989867,  3.01554958,  3.12952141],
       [ 1.16677458,  3.3700502 ,  3.17153716],
       [ 1.29521397,  2.31494576,  2.90802802],
       [ 1.47022956,  2.96325565,  3.97940825],
       [ 0.33881165,  3.40720619,  3.14824928],
       [ 2.12342091,  0.71004915,  4.56639293],
       [ 1.41646512,  1.01103071,  3.889