In [1]:
import numpy as np
import pandas as pd

In [2]:
lst = [5, 9, 11, -1, 4]
nar = np.array([5, 9, 11, -1, 4])

In [3]:
print(lst)
print(nar)

[5, 9, 11, -1, 4]
[ 5  9 11 -1  4]


In [4]:
ser1 = pd.Series([5, 9, 11, -1, 4])

In [5]:
print(ser1)

0     5
1     9
2    11
3    -1
4     4
dtype: int64


In [6]:
print(ser1.values)

[ 5  9 11 -1  4]


In [7]:
print(ser1.index)

RangeIndex(start=0, stop=5, step=1)


In [8]:
print(ser1[2])

11


In [9]:
print(nar[2])

11


In [10]:
ser2 = pd.Series([5, 9, 11, -1, 4], index = ['a', 'b', 'c', 'd', 'a'])

In [11]:
print(ser2)

a     5
b     9
c    11
d    -1
a     4
dtype: int64


In [12]:
print(ser2['a'])

a    5
a    4
dtype: int64


In [13]:
ser1.index = ['a', 'b', 'c', 'd', 'a']

In [14]:
print(ser1)

a     5
b     9
c    11
d    -1
a     4
dtype: int64


In [15]:
idx = ['a', 'b', 'c', 'd', 'a']
ser3 = pd.Series(lst, index=idx)

In [16]:
print(ser3)

a     5
b     9
c    11
d    -1
a     4
dtype: int64


In [17]:
ser1.name = "First series"

In [18]:
print(ser1)

a     5
b     9
c    11
d    -1
a     4
Name: First series, dtype: int64


In [19]:
ser1.index.name = "Character"

In [20]:
print(ser1)

Character
a     5
b     9
c    11
d    -1
a     4
Name: First series, dtype: int64


In [21]:
ser4 = pd.Series(lst, index=idx, dtype=float)

In [22]:
print(ser4)

a     5.0
b     9.0
c    11.0
d    -1.0
a     4.0
dtype: float64


In [23]:
print(nar)

[ 5  9 11 -1  4]


In [24]:
print(nar.dtype)

int32


In [25]:
ser5 = pd.Series(nar)

In [26]:
print(ser5)

0     5
1     9
2    11
3    -1
4     4
dtype: int32


In [27]:
ser5 = pd.Series(nar, dtype=np.int64)

In [28]:
print(ser5)

0     5
1     9
2    11
3    -1
4     4
dtype: int64


In [29]:
nar[0] = 0

In [30]:
print(ser5)

0     5
1     9
2    11
3    -1
4     4
dtype: int64


In [32]:
ser5[4] = 5

In [33]:
print(nar)

[ 0  9 11 -1  4]


In [34]:
n = np.array([1,2,3,4])

In [35]:
ser = pd.Series(n)

In [36]:
print(ser)

0    1
1    2
2    3
3    4
dtype: int32


In [37]:
n[3] = 0

In [38]:
print(ser)

0    1
1    2
2    3
3    0
dtype: int32


In [39]:
ser[3] = 4

In [40]:
print(n)

[1 2 3 4]


In [41]:
print(ser)

0    1
1    2
2    3
3    4
dtype: int32


In [42]:
ser6 = pd.Series(np.random.randn(5))

In [43]:
print(ser6)

0    1.468492
1    0.182280
2   -1.356522
3   -1.150014
4   -0.227964
dtype: float64


In [44]:
ser7 = pd.Series(np.arange(1, 6))

In [45]:
print(ser7)

0    1
1    2
2    3
3    4
4    5
dtype: int32


In [46]:
ser8 = pd.Series(np.zeros(4))
print(ser8)

0    0.0
1    0.0
2    0.0
3    0.0
dtype: float64


In [47]:
ser9 = pd.Series(8, index=idx)
print(ser9)

a    8
b    8
c    8
d    8
a    8
dtype: int64


In [48]:
d = {'a': 12, 'b': -1, 'c': 3}
ser10 = pd.Series(d)
print(ser10)

a    12
b    -1
c     3
dtype: int64


In [50]:
d = {'a': 12, 'b': -1, 'c': 3, 'd': 88}
idx = pd.Index(['a', 'b', 'd'])
ser11 = pd.Series(d, idx)
print(ser11)

a    12
b    -1
d    88
dtype: int64


In [51]:
t = [['a',2],['b',4],['c',3]]
idx, values = zip(*t)
ser12 = pd.Series(values, idx)
print(ser12)

a    2
b    4
c    3
dtype: int64
